export enum ExternalServiceAsInt {
  AzureBilling = 1,
  Basecamp = 2,
  Harvest = 3,
  NewRelic = 4,
  SLABAzure = 5,
  VisualStudioOnline = 6,
  JIRA = 7,
  Slack = 8,
  GitHub = 9,
  Sonar = 10,
  Jenkins = 11,
  ApplicationInsights = 12,
  Bitbucket = 13,
  BitbucketServer = 14,
  TFS = 15,
  Asana = 16,
  AWS = 17,
  Nuget = 18,
  Maven = 19,
  Npm = 20,
  TeamCity = 21,
  NVDVulnerabilities = 22,
  DocioApi = 23,
  DocioScanner = 24,
  GitLab = 25,
  Bamboo = 26,
  TravisCI = 27,
  CircleCI = 28,
}

export enum ServiceCategory {
  SCA = 'SCA',
  SourceRepos = 'SourceRepos',
  WorkTrackingTools = 'WorkTrackingTools',
  ContinuousIntegration = 'ContinuousIntegration',
  Performance = 'Performance',
  SAST = 'SAST',
}

export const ServiceCategoryDescription = {
  [ServiceCategory.SCA]: 'Software Composition Analysis',
  [ServiceCategory.SourceRepos]: 'Source Control',
  [ServiceCategory.WorkTrackingTools]: 'Work Item Tracking',
  [ServiceCategory.ContinuousIntegration]: 'Continuous Integration',
  [ServiceCategory.Performance]: 'Performance',
  [ServiceCategory.SAST]: 'Static Application Security Testing',
};

export enum ServiceConfiguration {
  Repository = 'repository',
  CodeAnalysisProject = 'code-analysis-project',
  RepositoryAndTrackingTool = 'repository-and-tracking-tool',
  TrackingTool = 'tracking-tool',
  PersonalAccessToken = 'connection',
  OAuth = 'oauth',
  ScanKeys = 'scan-keys',
}

export const ServiceConfigurationDescription = {
  [ServiceConfiguration.Repository]: '',
  [ServiceConfiguration.TrackingTool]: '',
  [ServiceConfiguration.RepositoryAndTrackingTool]: '',
  [ServiceConfiguration.PersonalAccessToken]: 'Connection',
  [ServiceConfiguration.OAuth]: 'Connection',
  [ServiceConfiguration.ScanKeys]: 'Scan Keys',
};

export enum ServiceStatus {
  Mapped = 'mapped',
  NotConnected = 'not-connected',
  Connected = 'connected',
  Disabled = 'disabled',
}

export enum ExternalService {
  AzureBilling = 'AzureBilling',
  Azure = 'Azure',
  Basecamp = 'Basecamp',
  Harvest = 'Harvest',
  NewRelic = 'NewRelic',
  SLABAzure = 'SLABAzure',
  VisualStudioOnline = 'VisualStudioOnline',
  JIRA = 'JIRA',
  Slack = 'Slack',
  GitHub = 'GitHub',
  Sonar = 'Sonar',
  Jenkins = 'Jenkins',
  ApplicationInsights = 'ApplicationInsights',
  Bitbucket = 'Bitbucket',
  BitbucketServer = 'BitbucketServer',
  TFS = 'TFS',
  Asana = 'Asana',
  AWS = 'AWS',
  Nuget = 'Nuget',
  Maven = 'Maven',
  Npm = 'Npm',
  TeamCity = 'TeamCity',
  NVDVulnerabilities = 'NVDVulnerabilities',
  DocioApi = 'DocioApi',
  DocioScanner = 'DocioScanner',
  GitLab = 'GitLab',
  Bamboo = 'Bamboo',
  React = 'React',
  ReactJ = 'React javascript',
  ReactT = 'React typescript',
  Angular = 'Angular',
  Java = 'Java',
  Phyton = 'Phyton',
  TravisCI = 'TravisCI',
  CircleCI = 'CircleCI',
  SonarQube = 'SonarQube',
  SecureCodeWarrior = 'SecureCodeWarrior',
}

export const externalServiceFromInt = { ...ExternalServiceAsInt };

export const serviceDescriptions: { [key: string]: string } = {
  [ExternalService.AzureBilling]: 'subscriptions/resources',
  [ExternalService.NewRelic]: 'integrations',
  [ExternalService.SLABAzure]: 'tables',
  [ExternalService.VisualStudioOnline]: 'team projects',
  [ExternalService.GitHub]: 'repositories',
  [ExternalService.Jenkins]: 'jobs',
  [ExternalService.ApplicationInsights]: 'integrations',
  [ExternalService.Bitbucket]: 'repositories',
  [ExternalService.BitbucketServer]: 'repositories',
  [ExternalService.TFS]: 'team projects',
  [ExternalService.Asana]: 'workspaces',
  [ExternalService.AWS]: 'resources',
  [ExternalService.GitLab]: 'repositories',
  [ExternalService.Bamboo]: 'jobs',
};

export const singularServiceDescriptions: { [key: string]: string } = {
  [ExternalService.AzureBilling]: 'subscription/resource',
  [ExternalService.NewRelic]: 'integration',
  [ExternalService.SLABAzure]: 'table',
  [ExternalService.VisualStudioOnline]: 'team project',
  [ExternalService.GitHub]: 'repository',
  [ExternalService.Jenkins]: 'job',
  [ExternalService.ApplicationInsights]: 'integration',
  [ExternalService.Bitbucket]: 'repository',
  [ExternalService.BitbucketServer]: 'repository',
  [ExternalService.TFS]: 'team project',
  [ExternalService.Asana]: 'workspace',
  [ExternalService.AWS]: 'resource',
  [ExternalService.GitLab]: 'repository',
  [ExternalService.Bamboo]: 'job',
};
