import { ExternalService } from './external-dataservice.model';

export const serviceDescriptionsIcons: { [key: string]: string } = {
  [ExternalService.Phyton]: 'fa-brands fa-python',
  [ExternalService.Java]: 'fa-brands fa-java',
  [ExternalService.Angular]: 'fa-brands fa-angular',
  [ExternalService.React]: 'fa-brands fa-react',
  [ExternalService.ReactJ]: 'fa-brands fa-react',
  [ExternalService.ReactT]: 'fa-brands fa-react',
  [ExternalService.GitLab]: 'fa-brands fa-gitlab',
  [ExternalService.Jenkins]: 'fa-brands fa-jenkins',
  [ExternalService.Bitbucket]: 'fa-brands fa-bitbucket',
  [ExternalService.GitHub]: 'fa-brands fa-github',
  [ExternalService.Azure]: 'fa-brands fa-windows',
  [ExternalService.VisualStudioOnline]: 'fa-brands fa-windows',
  [ExternalService.JIRA]: 'fa-brands fa-jira',
  [ExternalService.BitbucketServer]: 'fa-brands fa-bitbucket',
  [ExternalService.CircleCI]: 'ts-brands ts-circle-ci',
  [ExternalService.ApplicationInsights]: 'ts-brands ts-application-insights',
  [ExternalService.Bamboo]: 'ts-brands ts-bamboo',
  [ExternalService.NewRelic]: 'ts-brands ts-new-relic',
  [ExternalService.Sonar]: 'ts-brands ts-sonar',
  [ExternalService.DocioScanner]: 'ts-brands ts-tauruseer',
  [ExternalService.TravisCI]: 'ts-brands ts-travis-ci',
  [ExternalService.SecureCodeWarrior]: 'ts-brands ts-code-warrior',
};
